// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func InitService(dsn MySQLConnectString) (*BlogService, error) {
	mySQLConfig, err := NewMySQLConfig(dsn)
	if err != nil {
		return nil, err
	}
	mySQL, err := NewMySQL(mySQLConfig)
	if err != nil {
		return nil, err
	}
	userRepository, err := NewUserRepository(mySQL)
	if err != nil {
		return nil, err
	}
	articleRepository, err := NewArticleRepository(mySQL)
	if err != nil {
		return nil, err
	}
	blogService, err := NewBlogService(userRepository, articleRepository)
	if err != nil {
		return nil, err
	}
	return blogService, nil
}
