// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func InitService(file Filepath) (*HalfLiveCat, func(), error) {
	fileLogger, cleanup, err := NewFileLogger(file)
	if err != nil {
		return nil, nil, err
	}
	halfLiveCat, err := NewHalfLiveCat(fileLogger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return halfLiveCat, func() {
		cleanup()
	}, nil
}
