// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func InitService(cfg1 FooConfig, cfg2 BarConfig) (*FooBar, error) {
	foo := NewFoo(cfg1)
	bar, err := NewBar(cfg2)
	if err != nil {
		return nil, err
	}
	fooBar := NewFooBar(foo, bar)
	return fooBar, nil
}
