// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func InitCombine() *Service {
	foo := NewFoo()
	bar := NewBar()
	foobar := NewFoobar(foo, bar)
	service := &Service{
		f: foo,
		b: bar,
		m: foobar,
	}
	return service
}
