// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"io"
)

// Injectors from wire.go:

func InitLogger(out io.Writer) (Logger, error) {
	console := NewConsoleLogger(out)
	return console, nil
}
